apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
  labels:
        {{- include "mysql.selectorLabels" . | nindent 8 }}
data:
  DATABASE: {{ .Values.mysql.database }}

