apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
        {{- include "mysql.selectorLabels" . | nindent 8 }}
data:
  USER: {{ .Values.mysql.username | b64enc }}
  PASSWORD: {{ .Values.mysql.password | b64enc }}
  ROOT_PASSWORD: {{ .Values.mysql.rootPassword | b64enc }}
