apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mysql.fullname" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "mysql.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mysql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mysql.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-secrets
              prefix: MYSQL_
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: DATABASE
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: {{ .Release.Name }}-vol
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: {{ .Release.Name }}-vol
      spec:
        resources:
          requests:
            storage: 350Mi
        accessModes: [ "ReadWriteOnce" ]
